on:
  schedule:
    - cron: "7,35 * * * *"
  workflow_dispatch:
name: run scrapy
jobs:
  github-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@master
      # Upload from repo and fetch data packages in workspace (newer wins)
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: scrape data
        run: cd src && scrapy crawl homegate_flats
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA }}